"""add mealtimes

Revision ID: 1a5cb440a43b
Revises: 72af7551a58e
Create Date: 2020-12-27 11:34:59.487788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a5cb440a43b'
down_revision = '72af7551a58e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mealtimes', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'mealtimes', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mealtimes', type_='foreignkey')
    op.drop_column('mealtimes', 'user_id')
    # ### end Alembic commands ###
